config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  resources :hotels do 
    resources :reviews
  end
  resources :countries
  resources :notifications
  
  resources :cars do
    member do 
      patch :move
    end
  end
  root to: 'hotels#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @notifications = Notification.all.order("created_at DESC")
    end

    def show
        @notification = Notification.find(params[:id])
        @notification.update(opened: true) if @notification.opened == false
    end
end

app/views/notifications/_notification.html.erb
<div>
  <strong>
    <%= notification.title %>
</strong>
  <p>
    <%= notification.description%>
</p>
 <p>
    <%= notification.opened%>
</p>
</div>

app/views/notifications/index.html.erb
<div>
    <p><%= pluralize @notifications.count, "notification" %></p>
<p>
  <% @notifications.each do |notification| %>
    <%= render notification %>
    <!-- <%= render 'notification', notification: notification %> !-->
    <%= link_to "Show Notification", notification_path(notification), class: "btn btn-secondary" %>
  <% end %>
</p>
</div>

app/views/notifications/show.html.erb
<p> <%= render @notification %> </p>
<p> <%= link_to "Back to Notifications", notifications_path, class: "btn btn-secondary" %> </p>