config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  resources :hotels do 
    resources :reviews
  end
  resources :countries
  resources :notifications
  
  resources :cars do
    member do 
      patch :move
    end
  end
  root to: 'hotels#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/country.rb
class Country < ApplicationRecord
    validates :name, uniqueness: true
    has_many :hotels, dependent: :destroy
    has_many :tours, inverse_of: :country
    has_many :cars
    belongs_to :user
    accepts_nested_attributes_for :tours, reject_if: :all_blank, allow_destroy: true
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /countries or /countries.json
  def index
    @countries = Country.all
    
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
    @country.tours.new
  end

  # GET /countries/1/edit
  def edit
    if @country.tours.empty?
        @country.tours.new
    end
  end

  # POST /countries or /countries.json
  def create
    @country = current_user.countries.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, tours_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

  <p>
    <p><%= pluralize country.hotels.count, "hotel" %></p>
  </p>
</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

<h2> Tour </h2>
<div data-controller="nested-form">
  <template data-target="nested-form.template">
        <%= form.fields_for :tours, Tour.new, child_index: 'NEW_RECORD' do |tour| %>
        <%= render "tour_fields", form: tour %>
        <% end %>
  </template>
  <div>
        <%= form.fields_for :tours do |tour| %>
        <%= render "tour_fields", form: tour %>
        <% end %>
  </div>
  <div class="mb-3" data-target="nested-form.links">
  <%= link_to "Add Task", "#", class: "btn btn-outline-primary", data: { action: "click->nested-form#add_association"}%>
  </div>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/_tour_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
    <div>
        <%= form.label :name, style: "display: block" %>
        <%=form.text_field :name %>
        <small><%= link_to "Remove" , "#" , data: { action: "click->nested-form#remove_association"} %></small>
    </div>

<%= form.hidden_field :_destroy %>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country, class: "btn btn-light" %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Countries <%= link_to "Add New Country", new_country_path, class: "btn btn-light" %></h1>

<div id="countries">
  <% @countries.each do |country| %>
    <%= render country %>
    <p>
      <%= link_to "Show this country", country, class: "btn btn-secondary" %>
    </p>
  <% end %>
</div>

<div>
<%= link_to "Back to Adding a hotel", new_hotel_path, class: "btn btn-light" %>
</div>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path, class: "btn btn-light" %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<ul>
      <% @country.hotels.each do |hotel| %>
          <li><%= hotel.name %></li>
      <% end %>
</ul>

<div>
  <%= link_to "Edit this country", edit_country_path(@country), class: "btn btn-light" %> |
  <%= link_to "Back to countries", countries_path, class: "btn btn-light" %>

  <%= button_to "Destroy this country", @country, method: :delete, class: "btn btn-light text-danger" %>
</div>