config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  resources :hotels do 
    resources :reviews
  end
  resources :countries
  resources :notifications
  
  resources :cars do
    member do 
      patch :move
    end
  end
  root to: 'hotels#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :country
  belongs_to :user
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :address
  validates_presence_of :price
  validates_presence_of :contact_number
  has_rich_text :description
  has_many :reviews, dependent: :destroy
  after_update :send_updated_hotel_email
  before_destroy :send_deleted_hotel_email

  def send_updated_hotel_email
    HotelsMailer.updated(self).deliver_later
  end

  def send_deleted_hotel_email
    HotelsMailer.deleted(self.name).deliver_later
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /hotels or /hotels.json
  #def index
  #  @hotels = Hotel.all
  #end

  def index
    if params[:query].present?
      @hotels = Hotel.where("name LIKE ?", "%#{params[:query]}%")
    else
      @hotels = Hotel.all
    end
    #if turbo_frame_request?
      #render partial: "hotels", locals: { hotels: @hotels }
    #else
      #render "index"
    #end
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = current_user.hotels.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        CreateNotificationJob.perform_in(30.seconds, @hotel.id)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        UpdateNotificationJob.perform_in(30.seconds, @hotel.id)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    DeleteNotificationJob.perform_in(30.seconds, @hotel.name, @hotel.country.name)
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :description, :address, :country_id, :price, :contact_number)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.collection_select :country_id, Country.order(:name),:id,:name, include_blank: true %>
  </div>

  <div>
    <%= link_to "Add a Country", countries_path, class: "btn btn-light" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :contact_number, style: "display: block" %>
    <%= form.text_field :contact_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<!-- <div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hotel.description %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hotel.address %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= hotel.country.name%>
  </p>

  <p>
    <strong>Price:</strong>
    <%= hotel.price %>
  </p>

  <p>
    <strong>Contact number:</strong>
    <%= hotel.contact_number %>
  </p>

  <p>
    Added <%= time_tag hotel.created_at, "data-local": "time-ago" %>
  </p>

  <p>
    <strong><%= pluralize hotel.reviews.count, "review" %></strong>
  </p>

</div> -->

<div id="<%= dom_id hotel %>" class="card border-secondary mb-3" style="min-width: 350px;">
  <div class="card-body">
    <h5 class="card-title">Name: <%= hotel.name %></h5>
    <p class="card-text">Description: <%= hotel.description %></p>
    <p class="card-text">Address: <%= hotel.address %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Country: <%= hotel.country.name %></li>
    <li class="list-group-item">Price: <%= hotel.price %></li>
    <li class="list-group-item">Contact Number: <%= hotel.contact_number %></li>
  </ul>
  <div class="card-body">
    <h5 class="card-text">Added <%= time_tag hotel.created_at, "data-local": "time-ago" %></h5>
    <h5 class="card-text"><%= pluralize hotel.reviews.count, "review" %></h5>
  </div>
</div>

app/views/hotels/_hotels.html.erb
<%= turbo_frame_tag "hotels" do %>
<div id="hotels" class="d-flex justify-content-around flex-wrap">
  <% @hotels.each do |hotel| %>
  <div>
    <%= render hotel %>
      <div>
        <%= link_to "Show this hotel", hotel, data: { turbo: false, turbo_action: "advance"}, class: "btn btn-secondary ml-2" %>
      </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/hotels/_index.html+turbo_frame.erb
<!-- <%= turbo_frame_tag "hotels" do %>
  <%= render @hotels %>
<% end %> -->

app/views/hotels/_reviews.html.erb
<strong>Reviews</strong>

<div id="reviews">
<%# Expands to render partial: "reviews/review", coollection: hotel.reviews %>
<%= render hotel.reviews%>
</div>

<%= render "reviews/new", hotel: hotel, review: nil %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel, class: "btn btn-light" %> |
  <%= link_to "Back to hotels", hotels_path, class: "btn btn-light" %>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels <%= link_to "Add New Hotel", new_hotel_path, class: "btn btn-light" %> </h1>

  <%= form_with(url: hotels_path, method: "GET", data: { turbo_frame: "hotels", turbo_action: "advance", controller: "form-submission"}) do |form| %>
    <%= form.label :query, "Search by name:" %>
    <%= form.text_field :query, data: { action: "input->form-submission#search" } %>
  <% end %>

<%= render "hotels"%>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path, class: "btn btn-light" %>
</div>

app/views/hotels/show.html.erb
<%= turbo_stream_from @hotel %>
<p style="color: green"><%= notice %></p>

<%= render @hotel %>
<%= render "hotels/reviews", hotel: @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel), class: "btn btn-light" %> |
  <%= link_to "Back to hotels", hotels_path, class: "btn btn-light" %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete, class: "btn btn-light text-danger" %>
  <!-- <%= link_to "delete", @hotel, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %> -->
</div>