config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  resources :hotels do 
    resources :reviews
  end
  resources :countries
  resources :notifications
  
  resources :cars do
    member do 
      patch :move
    end
  end
  root to: 'hotels#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <!-- > <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"> -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="mx-4">
<!-- <nav>
  <%= link_to "Hotels", hotels_path %>
  <%= link_to "Countries", countries_path %>
</nav>
-->

      <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        <a class="navbar-brand" href="#">Hotel Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Hotels", hotels_path, class: "nav-item nav-link" %>
            <%= link_to "Countries", countries_path, class: "nav-item nav-link" %>
            <%= link_to "Notifications", notifications_path, class: "nav-item nav-link" %>
            <%= link_to "Car Rentals", cars_path, class: "nav-item nav-link" %>
            
            <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link", data: { turbo: false } %>
            <%= link_to "Log out", destroy_user_session_path, class: "nav-item nav-link", data: { turbo: false }, method: :delete %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link", data: { turbo: false } %>
            <%= link_to "Log in", new_user_session_path, class: "nav-item nav-link", data: { turbo: false } %>
            <% end %>
            
          </div>
        </div>
      </nav>
    <div class="container">
      <% if notice %> <div class="alert alert-info"><%= notice %></div> <% end %>
      <% if alert %> <div class="alert alert-warning"><%= alert %></div> <% end %>
     <%= yield %>
    </div>
  </body>
</html>